"""valuation_id on transaction

Revision ID: 208c0d25ef38
Revises: 769d6a847874
Create Date: 2026-09-14 20:56:41.019260
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '208c0d25ef38'
down_revision: Union[str, None] = '769d6a847874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('valuation_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_transaction_valuation_id'), 'transaction', ['valuation_id'], unique=False)
    op.create_foreign_key('transaction_valuation_id_fkey', 'transaction', 'valuation', ['valuation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_valuation_id_fkey', 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_valuation_id'), table_name='transaction')
    op.drop_column('transaction', 'valuation_id')
    # ### end Alembic commands ###
