"""account and valuation tables

Revision ID: 749e15077f93
Revises: 
Create Date: 2026-09-13 22:32:30.792367
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '749e15077f93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('on_budget', sa.Boolean(), nullable=False),
    sa.Column('on_budget_floor_cents', sa.BigInteger(), nullable=False),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=True),
    sa.Column('annual_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('compounding_rule', sa.String(), nullable=True),
    sa.Column('statement_close_day', sa.Integer(), nullable=True),
    sa.Column('grace_days', sa.Integer(), nullable=True),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('amortization_end', sa.Date(), nullable=True),
    sa.Column('prepayment_model', sa.String(), nullable=True),
    sa.Column('promo_expiry_date', sa.Date(), nullable=True),
    sa.Column('deferred_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('minimum_payment_rule', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_owner_id'), 'account', ['owner_id'], unique=False)
    op.create_index('ix_account_owner_lower_name', 'account', ['owner_id', sa.text('lower(name)')], unique=True)
    op.create_table('valuation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_account_id'), 'valuation', ['account_id'], unique=False)
    op.create_index(op.f('ix_valuation_owner_id'), 'valuation', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuation_owner_id'), table_name='valuation')
    op.drop_index(op.f('ix_valuation_account_id'), table_name='valuation')
    op.drop_table('valuation')
    op.drop_index('ix_account_owner_lower_name', table_name='account')
    op.drop_index(op.f('ix_account_owner_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
