"""category, transaction, account_line, category_line tables

Revision ID: 769d6a847874
Revises: 749e15077f93
Create Date: 2026-09-14 12:43:04.150747
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '769d6a847874'
down_revision: Union[str, None] = '749e15077f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_owner_id'), 'category', ['owner_id'], unique=False)
    op.create_index('ix_category_owner_lower_name', 'category', ['owner_id', sa.text('lower(name)')], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('payee_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_owner_id'), 'transaction', ['owner_id'], unique=False)
    op.create_table('account_line',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('cents', sa.BigInteger(), nullable=False),
    sa.Column('budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_line_account_id'), 'account_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_line_owner_id'), 'account_line', ['owner_id'], unique=False)
    op.create_index(op.f('ix_account_line_transaction_id'), 'account_line', ['transaction_id'], unique=False)
    op.create_table('category_line',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('cents', sa.BigInteger(), nullable=False),
    sa.Column('need_level', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_line_category_id'), 'category_line', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_line_owner_id'), 'category_line', ['owner_id'], unique=False)
    op.create_index(op.f('ix_category_line_transaction_id'), 'category_line', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_line_transaction_id'), table_name='category_line')
    op.drop_index(op.f('ix_category_line_owner_id'), table_name='category_line')
    op.drop_index(op.f('ix_category_line_category_id'), table_name='category_line')
    op.drop_table('category_line')
    op.drop_index(op.f('ix_account_line_transaction_id'), table_name='account_line')
    op.drop_index(op.f('ix_account_line_owner_id'), table_name='account_line')
    op.drop_index(op.f('ix_account_line_account_id'), table_name='account_line')
    op.drop_table('account_line')
    op.drop_index(op.f('ix_transaction_owner_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('ix_category_owner_lower_name', table_name='category')
    op.drop_index(op.f('ix_category_owner_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
