"""payee table and payee_id fk

Revision ID: ffe95c16a43c
Revises: 208c0d25ef38
Create Date: 2026-09-15 15:15:08.585883
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ffe95c16a43c'
down_revision: Union[str, None] = '208c0d25ef38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('archived_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payee_owner_id'), 'payee', ['owner_id'], unique=False)
    op.create_index('ix_payee_owner_lower_name', 'payee', ['owner_id', sa.text('lower(name)')], unique=True, postgresql_where=sa.text('archived_on IS NULL'))
    op.create_index(op.f('ix_transaction_payee_id'), 'transaction', ['payee_id'], unique=False)
    op.create_foreign_key('fk_transaction_payee_id_payee', 'transaction', 'payee', ['payee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_payee_id_payee', 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_payee_id'), table_name='transaction')
    op.drop_index('ix_payee_owner_lower_name', table_name='payee', postgresql_where=sa.text('archived_on IS NULL'))
    op.drop_index(op.f('ix_payee_owner_id'), table_name='payee')
    op.drop_table('payee')
    # ### end Alembic commands ###
